### ISSUE TITLE
warn students that zooming their browsers will affect test results

### ISSUE THREAD

**Issue by cameronwp** [udacity/frontend-grading-engine#17]
I've seen some complaints that zooming prevents tests from passing, especially when tests are related to any kind of pixel calculation. Let's consider adding a feature where we warn students to stay at 100% zoom so that tests pass.

The alternative is to actually account for zoom with pixel calculations. My intuition is that this is more trouble than its worth, but I could be wrong.

**Comment by notetiene** [comment]
Is it related to the new version or the extension in general?

Do you have an example of the issue?

**Comment by cameronwp** [comment]
In general. [This quiz](
http://udacity.github.io/fend/lessons/L5/problem-set/07-making-peach-ice-cream/index.html)
is reported to have failed when zoomed in.

Just to be clear, this is not an urgent issue.

**Comment by notetiene** [comment]
I can't replicate the issue when zooming.

**Comment by notetiene** [comment]
I've tried both Chrome and Firefox in many ways and I'm unable to replicate the issue when zooming. It might have been fixed with the `position` fixes.
