### ISSUE TITLE
Udacity Feedback Extension not recognize font awesome icon

### ISSUE THREAD

**Issue by satyakresna** [udacity/frontend-grading-engine#23]
Hi team, thanks for providing [Responsive Images](https://www.udacity.com/course/responsive-images--ud882) as a good course for me. It's a good thing that web developer should care about images, typography when develop website. When I'm using [fontawesome](http://fontawesome.io/) to get facebook, twitter, google+, and digg, the Udacity feedback extension doesn't respons it (I have refresh it several times in Google Chrome browser). This is the screenshot:

![responsive images feedback course](https://cloud.githubusercontent.com/assets/11099186/18504073/f232c12e-7a92-11e6-89c6-f5600181f670.png)

This is the [Gist Code](https://gist.github.com/satyakresna/708f2c15b5d22c6ba76435385ddc49a1)

But, when I see your project-2 solution, it use the [We Love Font Icons](http://weloveiconfonts.com/) website as the provider font icon. Why only this website can recognized by Udacity feedback extension? I think it should be fix it, so that's not only We Love Font Icons but Font awesome and other font icons website can recognized by Udacity feedback extension. Thank you very much.

P.S. I have give this issue on [responsive-images](https://github.com/udacity/responsive-images) repository. I give this issue on this repo to get your fast response answer.

**Comment by notetiene** [comment]
Since it was already reported in the [responsive-images](https://github.com/udacity/responsive-images) course and it's not related to the extension itself. I'm closing it.

**Comment by notetiene** [comment]
Since it was already reported in the responsive-images course and it's not related to the extension itself. I'm closing it.
