### ISSUE TITLE
Test not being evaluated correctly [Chrome 63]

### ISSUE THREAD

**Issue by aviaryan** [udacity/frontend-grading-engine#34]
The test I am referring to is at http://udacity.github.io/fend/lessons/L3/problem-set/08-udacity-site-header/index.html. 
No matter what you try, you can't pass the "The font-weight of the header text is 400" test on Chrome 63. 
This seems to be a bug as it works on older Chrome versions.

**Comment by NikiKot** [comment]
I have the same problem too...

**Comment by kammitama5** [comment]
Me too. I experienced this also.

**Comment by forbiddenvoid** [comment]
This is unrelated to the actual extension itself and was an issue with that particular test. That's been resolved, and I'm closing this for now.
