### ISSUE TITLE
Font sizing is affected by body

### ISSUE THREAD

**Issue by cameronwp** [udacity/frontend-grading-engine#8]
Noticed by @jamesparkes: if you set font-size for the body, it also affects the font-size of the text in the feedback widget. it might be worth giving the text in the widget some default styling

**Comment by notetiene** [comment]
Thanks for noticing. Since CSS may easily collide, I think we'll use an iFrame.

**Comment by cameronwp** [comment]
Awesome! An iFrame seems like a reasonable approach.

**Comment by notetiene** [comment]
Using an iFrame fixed the problem.
